name: appium_handler
description: "A handler for appium flutter driver"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    path: ../flutter_driver
    #sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  vm_service: ^13.0.0
  package_info_plus: ^6.0.0
  process_run: ^0.14.2
  xml: ^6.5.0
  uuid: ^4.3.3
  flutter_email_sender: ^6.0.2
  logging: ^1.2.0
  dtd: ^2.2.0
  pointer_interceptor: ^0.9.3+7  #^0.10.1
  ansi_up: ^1.0.0
  collection: ^1.18.0
  intl: ^0.19.0
  meta: ^1.11.0
  mime: ^1.0.5
  dap: ^1.2.0
  codicon: ^1.0.0
  provider: ^6.1.2
  url_launcher: ^6.2.5
  path: ^1.9.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.0
  extension_discovery: ^2.0.0
  usage: ^4.1.1
#  web: ^0.5.1
  shared_preferences: ^2.2.2
  vm_snapshot_analysis: ^0.7.6
  flutter_markdown: ^0.6.22+1
  image: ^4.1.7
  fixnum: ^1.1.0
  vm_service_protos: ^1.0.0
  flutter_riverpod: ^2.5.1
  stack_trace: ^1.11.1
  devtools_app_shared: any
  dds_service_extensions: ^1.6.2
  file_selector: ^1.0.3
  http: ^1.2.1
  clock: ^1.1.1
  async: ^2.11.0
  string_scanner: ^1.2.0
  devtools_shared: ^6.0.4
#  flutter_web_plugins: any
  unified_analytics: ^6.0.0
# js: ^0.6.7
  path_provider: ^2.1.3
  characters: ^1.3.0
  vector_math: ^2.1.4
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
  uses-material-design: true

  assets:
    - assets/dart_syntax.json
